//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunicationsCompany.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTariff
    {
        public int ClientTariffId { get; set; }
        public int UserId { get; set; }
        public int TariffId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Tariff Tariff { get; set; }
        public virtual User User { get; set; }
    }
}
